language: generic 
sudo: required
services:
   - docker

before_install:
   - docker build -t yrosner/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yrosner/docker-react npm run test
